### ISSUE TITLE
alias handler fails on the case insensitivity of domain names.

### ISSUE THREAD

**Issue by paultaiton** [paultaiton/cloudmra#7]
Processing 1 new email messages.
detected unhandled Python exception in '/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py'
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 91, in <module>
    sys.exit(main())
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 84, in main
    main_overseer.process()
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 44, in process
    default = self.alias.get_default(list(receipients)[0])
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/aliashandler.py", line 50, in get_default
    response = self.domains[host].get_default()
KeyError: 'CAPITAL.DOMAIN'

**Comment by paultaiton** [comment]
Should be resolved by #9
