### ISSUE TITLE
lmtp delivery fails with unicode characters

### ISSUE THREAD

**Issue by paultaiton** [paultaiton/cloudmra#8]
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 91, in <module>
    sys.exit(main())
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 84, in main
    main_overseer.process()
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/__main__.py", line 51, in process
    if (self.outhandler.deliver(message, i)):
  File "/home/cloudmra/.local/lib/python3.7/site-packages/cloudmra/deliveryhandler.py", line 22, in deliver
    self.lmtp.sendmail(from_addr='', to_addrs=receipient, msg=message)
  File "/usr/lib64/python3.7/smtplib.py", line 855, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 10431: ordinal not in range(128)

**Comment by paultaiton** [comment]
Should be resolved by #9
